version: "3.9"
services:
  gateway:
    image: nginx:1.20
    volumes:
        - ./:/opt
    ports:
        - "8443:443"
    working_dir: /opt
    entrypoint: bash boot.sh
  backend:
    image: nginx:1.20
    ports:
        - "8080:80"
    
