version: "3.9"
services:
  gateway:
    image: nginx:1.20
    volumes:
      - ./:/opt
    ports:
      - "8443:443"
    working_dir: /opt
    entrypoint: bash boot.sh
  backend:
    image: rodolpheche/wiremock:main
    volumes:
      - ./wiremock/stubs:/home/wiremock
    entrypoint:
      - "/docker-entrypoint.sh"
      - "--verbose"
    
